### ISSUE TITLE
momentjs Error

### ISSUE THREAD

**Issue by jimmycasey** [IonicaBizau/git-stats-html#14]
Hi,

I'm trying to dockerize my usage of git-stats but i'm hitting this error:

`git-stats --global-activity --raw -s '2017-05-15' | git-stats-html -o ../views/out.html
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Aug 27, 2019, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/opt/dit_dashboard/node_modules/moment/moment.js:320:98)
    at configFromString (/opt/dit_dashboard/node_modules/moment/moment.js:2385:15)
    at configFromInput (/opt/dit_dashboard/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/opt/dit_dashboard/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/opt/dit_dashboard/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/opt/dit_dashboard/node_modules/moment/moment.js:2648:16)
    at createLocal (/opt/dit_dashboard/node_modules/moment/moment.js:2652:16)
    at hooks (/opt/dit_dashboard/node_modules/moment/moment.js:12:29)
    at render (/opt/dit_dashboard/node_modules/git-stats-html2/app.js:43:10)
    at Socket.<anonymous> (/opt/dit_dashboard/node_modules/git-stats-html2/app.js:23:5)
`

The git-stats output seems fine but when I pipe it to git-stats-html this occurs.
My Dockerfile inherits from node:8.16.1-alpine.
I have tried loads of different base images but no joy.

Any help would be great, thanks.

**Comment by jimmycasey** [comment]
Error was actually associated with git-stats-html2
