### ISSUE TITLE
Any inclusion of ~/.git-stats-config.js results in TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by bfeist** [IonicaBizau/git-stats-html#19]
Using the default `.git-stats-config.js` example at `https://github.com/IonicaBizau/git-stats` or one that contains any permutation of options results in an error in `git-stats-html`

Tested in both macOS and Windows.

Error as follows:
```
git-stats --since "1 january 2019" --raw | git-stats-html -o out.html --big
/npm/node_modules/git-stats-html/lib/index.js:25
    json.levels.forEach(function (c, weekIndex) {
                ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at gitStatsHtml (index.js:25:17)
    at Tilda.<anonymous> (git-stats-html:35:5)
    at Tilda.emit (node:events:526:28)
    at Tilda.parse (/tilda/lib/index.js:567:18)
    at Socket.<anonymous> (/tilda/lib/index.js:330:28)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)

**Comment by dodwmd** [comment]
Same error in Linux Mint:

```
/home/linuxbrew/.linuxbrew/lib/node_modules/git-stats-html/lib/index.js:25
    json.levels.forEach(function (c, weekIndex) {
                ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at gitStatsHtml (/home/linuxbrew/.linuxbrew/lib/node_modules/git-stats-html/lib/index.js:25:17)
    at Tilda.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/git-stats-html/bin/git-stats-html:35:5)
    at Tilda.emit (node:events:513:28)
    at Tilda.parse (/home/linuxbrew/.linuxbrew/lib/node_modules/git-stats-html/node_modules/tilda/lib/index.js:567:18)
    at /home/linuxbrew/.linuxbrew/lib/node_modules/git-stats-html/node_modules/tilda/lib/index.js:323:24
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.8.0
```
