### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Sevyls** [IonicaBizau/git-stats-html#3]
Environment: 
OS: Windows 7 Enterprise
NodeJs: v7.4.0
NPM 4.0.5
Git Bash

I am getting an error on trying to use git-stats-html:

``` git-stats -s '1 January 2016' --raw | git-stats-html -o stats.html
D:\Users\**\AppData\Roaming\npm\node_modules\git-stats-html\lib\index.js:25
    json.levels.forEach(function (c, weekIndex) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at gitStatsHtml (D:\Users\**\AppData\Roaming\npm\node_modules\git-stats-html\lib\index.js:25:16)
    at Tilda.main.action (D:\Users\**\AppData\Roaming\npm\node_modules\git-stats-html\bin\git-stats-html:35:5)
    at emitOne (events.js:96:13)
    at Tilda.emit (events.js:188:7)
    at Tilda.parse (D:\Users\**\AppData\Roaming\npm\node_modules\git-stats-html\node_modules\tilda\lib\index.js:575:18)
    at D:\Users\**\AppData\Roaming\npm\node_modules\git-stats-html\node_modules\tilda\lib\index.js:323:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at display (D:\Users\**\AppData\Roaming\npm\node_modules\git-stats\bin\git-stats:187:24)
    at D:\Users\**\AppData\Roaming\npm\node_modules\git-stats\lib\index.js:513:9
    at D:\Users\**\AppData\Roaming\npm\node_modules\git-stats\lib\index.js:414:9
```

**Comment by IonicaBizau** [comment]
Hmm, sounds like a bug. Can you paste the exact command you executed? Thanks!

**Comment by driade** [comment]
Same here.

MacOS latest
NPM 2.14.2
Bash

```
/usr/local/lib/node_modules/git-stats-html/lib/index.js:25
    json.levels.forEach(function (c, weekIndex) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at gitStatsHtml (/usr/local/lib/node_modules/git-stats-html/lib/index.js:25:16)
    at Tilda.<anonymous> (/usr/local/lib/node_modules/git-stats-html/bin/git-stats-html:35:5)
    at emitOne (events.js:77:13)
    at Tilda.emit (events.js:169:7)
    at Tilda.parse (/usr/local/lib/node_modules/git-stats-html/node_modules/tilda/lib/index.js:575:18)
    at /usr/local/lib/node_modules/git-stats-html/node_modules/tilda/lib/index.js:323:24
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
```

I paste the command and also a copy of the data used.

Thanks!

git-stats --raw | git-stats-html -o out.html

[data.txt](https://github.com/IonicaBizau/git-stats-html/files/722314/data.txt)

**Comment by IonicaBizau** [comment]
I'm on it!

**Comment by IonicaBizau** [comment]
Addressed here: https://github.com/IonicaBizau/tilda/pull/14

`npm i -g git-stats-html@latest` should bring you the fix. :tada:
