### ISSUE TITLE
git-stats --authors results in TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Sevyls** [IonicaBizau/git-stats-html#4]
After the successful fix of #3, I'm getting an error with git-stats-html@latest on running git-stats-html with authors data from git-stats:

```
$ git-stats -s '1 January 2016' --authors --raw | git-stats-html -o authors.html
D:\Users\***\AppData\Roaming\npm\node_modules\git-stats-html\lib\index.js:25
    json.levels.forEach(function (c, weekIndex) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at gitStatsHtml (D:\Users\***\AppData\Roaming\npm\node_modules\git-stats-html\lib\index.js:25:16)
    at Tilda.main.action (D:\Users\***\AppData\Roaming\npm\node_modules\git-stats-html\bin\git-stats-html:35:5)
    at emitOne (events.js:96:13)
    at Tilda.emit (events.js:188:7)
    at Tilda.parse (D:\Users\***\AppData\Roaming\npm\node_modules\git-stats-html\node_modules\tilda\lib\index.js:577:18)
    at Socket.<anonymous> (D:\Users\***\AppData\Roaming\npm\node_modules\git-stats-html\node_modules\tilda\lib\index.js:332:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

Raw output:
``$ git-stats -s '1 January 2016' --authors --raw``

```json 
{
  "legend":true,
  "flat":true,
  "no_ansi":false,
  "authors": [
    {"value":149,"label":"Developer2"},
    {"value":55,"label":"Developer1"},
    {"value":27,"label":"Developer3"}, 
    {"value":7,"label":"Developer4"},
    {"value":4,"label":"Developer5"}
  ]
}
```

**Comment by IonicaBizau** [comment]
Well, because the JSON output by `--authors` is not yet understandable by this tool. We probably want to generate a nice pie chart in that case, but that's not yet implemented.
